<html>

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1251">
<meta name=Generator content="Microsoft Word 15 (filtered)">
<title>FamilyGuide3_Home</title>
<style>
<!--
 /* Font Definitions */
 @font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin-top:0cm;
	margin-right:0cm;
	margin-bottom:8.0pt;
	margin-left:0cm;
	line-height:107%;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{color:#0563C1;
	text-decoration:underline;}
a:visited, span.MsoHyperlinkFollowed
	{color:#954F72;
	text-decoration:underline;}
p.MsoListParagraph, li.MsoListParagraph, div.MsoListParagraph
	{margin-top:0cm;
	margin-right:0cm;
	margin-bottom:8.0pt;
	margin-left:36.0pt;
	line-height:107%;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
p.MsoListParagraphCxSpFirst, li.MsoListParagraphCxSpFirst, div.MsoListParagraphCxSpFirst
	{margin-top:0cm;
	margin-right:0cm;
	margin-bottom:0cm;
	margin-left:36.0pt;
	margin-bottom:.0001pt;
	line-height:107%;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
p.MsoListParagraphCxSpMiddle, li.MsoListParagraphCxSpMiddle, div.MsoListParagraphCxSpMiddle
	{margin-top:0cm;
	margin-right:0cm;
	margin-bottom:0cm;
	margin-left:36.0pt;
	margin-bottom:.0001pt;
	line-height:107%;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
p.MsoListParagraphCxSpLast, li.MsoListParagraphCxSpLast, div.MsoListParagraphCxSpLast
	{margin-top:0cm;
	margin-right:0cm;
	margin-bottom:8.0pt;
	margin-left:36.0pt;
	line-height:107%;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
span.UnresolvedMention1
	{mso-style-name:"Unresolved Mention1";
	color:#605E5C;
	background:#E1DFDD;}
span.UnresolvedMention2
	{mso-style-name:"Unresolved Mention2";
	color:#605E5C;
	background:#E1DFDD;}
.MsoChpDefault
	{font-family:"Calibri",sans-serif;}
.MsoPapDefault
	{margin-bottom:8.0pt;
	line-height:107%;}
@page WordSection1
	{size:595.3pt 841.9pt;
	margin:42.5pt 42.5pt 42.5pt 70.85pt;}
div.WordSection1
	{page:WordSection1;}
 /* List Definitions */
 ol
	{margin-bottom:0cm;}
ul
	{margin-bottom:0cm;}
-->
</style>

</head>

<body lang=EN-US link="#0563C1" vlink="#954F72">

<div class=WordSection1>

<p class=MsoNormal align=center style='text-align:center'><b><u><span lang=UK
style='font-size:20.0pt;line-height:107%'>Guide for Family 3 :(</span></u></b></p>

<p class=MsoNormal align=right style='margin-left:18.0pt;text-align:right'><span
lang=UK style='font-size:14.0pt;line-height:107%'>&nbsp;</span></p>

<p class=MsoNormal align=right style='margin-left:18.0pt;text-align:right'><span
lang=UK style='font-size:14.0pt;line-height:107%'>березень 2020 - листопад 2022</span></p>

<p class=MsoNormal style='margin-left:18.0pt'><i><span lang=UK>&nbsp;</span></i></p>

<p class=MsoNormal style='margin-left:18.0pt'><i><span lang=UK>Всi малюнки -
~15% вiд оригiнального, можна збiльшити для деталiзацiї, чи подивитися
оригiнали в папцi </span></i><i>Pics</i><i><span lang=RU>.</span></i></p>

<p class=MsoNormal style='margin-left:18.0pt'><i><span lang=UK>До всього
вiдноситися критично, можуть бути помилки, описки, недавнi змiни якi не внесенi
в цей файл.</span></i></p>

<p class=MsoNormal align=right style='margin-left:18.0pt;text-align:right'><span
lang=UK>&nbsp;</span></p>

<p class=MsoListParagraphCxSpFirst style='text-indent:-18.0pt'><b><span
lang=UK style='font-size:14.0pt;line-height:107%'>1.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></b><b><span lang=UK style='font-size:14.0pt;line-height:107%'>Електрика</span></b><b><span
style='font-size:14.0pt;line-height:107%'><br>
<a href="FamilyGuide3_Home1.htm"><span style='color:windowtext;text-decoration:
none'><img border=0 width=101 height=66
src="Pics/image001.png"></span></a></span></b></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt'><b><span
lang=UK style='font-size:14.0pt;line-height:107%'>2.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></b><b><span lang=UK style='font-size:14.0pt;line-height:107%'>Вода<br>
</span></b><b><span style='font-size:14.0pt;line-height:107%'><a
href="FamilyGuide3_Home2.htm"><span style='color:windowtext;text-decoration:
none'><img border=0 width=101 height=66
src="Pics/image002.png"></span></a></span></b></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt'><b><span
lang=UK style='font-size:14.0pt;line-height:107%'>3.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></b><b><span lang=UK style='font-size:14.0pt;line-height:107%'>Вигрiбна
яма</span></b></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:72.0pt;text-indent:-18.0pt'><span
lang=UK>a.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span lang=UK>Викачка - 067 159 4646; 097 492 8077</span></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt'><b><span
lang=UK style='font-size:14.0pt;line-height:107%'>4.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></b><b><span lang=UK style='font-size:14.0pt;line-height:107%'>Ворота<br>
<a href="FamilyGuide3_Home4.htm"><span style='color:windowtext;text-decoration:
none'><img border=0 width=101 height=66
src="Pics/image003.png"></span></a></span></b></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt'><b><span
lang=UK style='font-size:14.0pt;line-height:107%'>5.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></b><b><span lang=UK style='font-size:14.0pt;line-height:107%'>Опалення<br>
<a href="FamilyGuide3_Home5.htm"><span style='color:windowtext;text-decoration:
none'><img border=0 width=101 height=66
src="Pics/image004.png"></span></a></span></b></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt'><b><span
lang=UK style='font-size:14.0pt;line-height:107%'>6.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></b><b><span lang=UK style='font-size:14.0pt;line-height:107%'>Кондицiонери</span></b></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:72.0pt;text-indent:-18.0pt'><span
lang=UK>a.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span lang=UK>Олександр 097 244 9100</span></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt'><b><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>7.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span></b><b><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>Баня</span></b></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:72.0pt;text-indent:-18.0pt'><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>a.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>Сауна</span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:72.0pt;text-indent:-18.0pt'><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>b.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>Вентиляцiя</span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:72.0pt;text-indent:-18.0pt'><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>c.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>Вода</span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:72.0pt;text-indent:-18.0pt'><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>d.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>Каналiзацiя</span></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt'><b><span
lang=UK style='font-size:14.0pt;line-height:107%'>8.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></b><b><span lang=UK style='font-size:14.0pt;line-height:107%'>Охорона<br>
<a href="FamilyGuide3_Home8.htm"><span style='color:windowtext;text-decoration:
none'><img border=0 width=101 height=66
src="Pics/image005.png"></span></a></span></b></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt'><b><span
lang=UK style='font-size:14.0pt;line-height:107%'>9.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></b><b><span lang=UK style='font-size:14.0pt;line-height:107%'>Iнтернет+<br>
<a href="FamilyGuide3_Home9.htm"><span style='color:windowtext;text-decoration:
none'><img border=0 width=101 height=66
src="Pics/image006.png"></span></a></span></b></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt'><b><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>10.</span></b><b><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>Комп'ютери+</span></b></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:72.0pt;text-indent:-18.0pt'><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>a.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>Apple</span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:72.0pt;text-indent:-18.0pt'><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>b.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>Ноутбуки</span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:72.0pt;text-indent:-18.0pt'><span
lang=UK style='font-size:14.0pt;line-height:107%'>c.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span lang=UK style='font-size:14.0pt;line-height:107%'>Software</span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:108.0pt;text-indent:
-108.0pt'><span lang=UK><span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>i.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><a href="file://VINM0709/D$/DOCS/Private/ProduKey/"><span
lang=UK>DOCS\Private\ProduKey\</span></a><span lang=UK> - Product Keys (офiцiйнi
Windows лiцензiї) для всiх комп'ютерiв/ноутбукiв (все куплено або окремо або
разом з комп'ютером)</span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:108.0pt;text-indent:
-108.0pt'><span lang=UK><span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>ii.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span lang=UK>Office 365 Home - сплачена лiцензiя на 6
користувачiв (наступний платiж <span style='background:aqua'>14 квiтня 2023</span>),
для кожного:</span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:144.0pt;text-indent:
-18.0pt'><span lang=UK>1)<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span lang=UK>Office на 5 пристроях одночасно (наприклад, iPhone,
iPad, notebook, комп'ютер)</span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:144.0pt;text-indent:
-18.0pt'><span lang=UK>2)<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span lang=UK>Хмарне сховище OneDrive обсягом 1 ТБ</span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:144.0pt;text-indent:
-18.0pt'><span lang=UK>3)<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span lang=UK>60 хвилин на мiсяць у Skype</span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:72.0pt;text-indent:-18.0pt'><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>d.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>Моноблоки</span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:72.0pt;text-indent:-18.0pt'><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>e.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>Сервери</span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:72.0pt;text-indent:-18.0pt'><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>f.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>Принтери</span></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt'><b><span
lang=UK style='font-size:14.0pt;line-height:107%'>11.</span></b><b><span
lang=UK style='font-size:14.0pt;line-height:107%'>ТВ +</span></b></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:72.0pt;text-indent:-18.0pt'><span
lang=UK>a.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><s><span lang=UK style='font-size:14.0pt;line-height:107%'>DLNA</span></s><span
lang=UK style='font-size:14.0pt;line-height:107%'> </span><span lang=RU
style='font-size:14.0pt;line-height:107%;color:red'>&lt;</span><span
style='font-size:14.0pt;line-height:107%;color:red'>UPD</span><span lang=RU
style='font-size:14.0pt;line-height:107%;color:red'> серпень 2022&gt;</span><span
lang=RU> (</span><span lang=UK>бiльше не використовується</span><span lang=RU>)</span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:72.0pt;text-indent:-18.0pt'><span
lang=UK style='background:yellow'>b.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span lang=UK style='font-size:14.0pt;line-height:107%;
background:yellow'>DuneHD (</span><span style='font-size:14.0pt;line-height:
107%;background:yellow'>4</span><span lang=UK style='font-size:14.0pt;
line-height:107%;background:yellow'>)</span><span style='background:yellow'> - </span><span
lang=UK style='background:yellow'>вiтальня, Лада, спальня, баня</span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:72.0pt;text-indent:-18.0pt'><span
lang=UK style='background:yellow'>c.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span lang=UK style='font-size:14.0pt;line-height:107%;
background:yellow'>AppleTV (4)</span><span lang=UK style='background:yellow'> -
вiтальня, кабiнет, кухня, баня</span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:72.0pt;text-indent:-18.0pt'><span
lang=UK>d.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span lang=UK style='font-size:14.0pt;line-height:107%'>T2 та
супутник - </span><span lang=UK>кабелi вiд антени та тарiлки виведенi в нижню
праву шафу в котельнiй, далi роздаються на кiмнати через splitter'и</span></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt'><b><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>12.</span></b><b><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>Вiтальня -
домашнiй кiнотеатр</span></b></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt'><b><span
lang=UK style='font-size:14.0pt;line-height:107%'>13.</span></b><b><span
lang=UK style='font-size:14.0pt;line-height:107%'>Smart Home (Fibaro</span></b><b><span
style='font-size:14.0pt;line-height:107%'> HC2</span></b><b><span lang=UK
style='font-size:14.0pt;line-height:107%'>) </span></b><span lang=UK
style='font-size:14.0pt;line-height:107%;color:red'>&lt;UPD вересень 2022&gt;<br>
</span><b><span lang=UK style='font-size:14.0pt;line-height:107%'><a
href="FamilyGuide3_Home13.htm"><span style='color:windowtext;text-decoration:
none'><img border=0 width=101 height=66
src="Pics/image007.png"></span></a></span></b></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt'><b><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>14.</span></b><b><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>Басейн</span></b></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt'><b><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>15.</span></b><b><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>Фонтан</span></b></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt'><b><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>16.</span></b><b><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>Автополивання</span></b></p>

<p class=MsoListParagraphCxSpMiddle style='margin-left:72.0pt;text-indent:-18.0pt'><span
lang=UK>a.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span lang=UK>Микола Петров 096 372 0354</span></p>

<p class=MsoListParagraphCxSpMiddle style='text-indent:-18.0pt'><b><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>17.</span></b><b><span
lang=UK style='font-size:14.0pt;line-height:107%;background:yellow'>Акварiум/риби</span></b></p>

<p class=MsoListParagraphCxSpLast style='margin-left:72.0pt;text-indent:-18.0pt'><span
lang=UK>a.<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span lang=UK>Микола Паламарчук 097 698 5970</span></p>

</div>

</body>

</html>
